### PR TITLE
39 errors in projectr method for sparse matrix data

### LINKED ISSUE #39: Errors in projectR method for sparse matrix data
There is a method to run projectR on sparse data, but it fails with an error. 
https://github.com/genesofeve/projectR/blob/39b3b0fdda3cca5419fa424705c79e979acef2a7/R/projectR.R#L88

To reproduce:

```
load("data/p.RNAseq6l3c3t.RData")
load("data/CR.RNAseq6l3c3t.RData")

data <- as(p.RNAseq6l3c3t, "sparseMatrix")
loadings <- CR.RNAseq6l3c3t@featureLoadings
class(data)
class(loadings)

projectR(data, loadings)
```
```
[1] "108 row names matched between data and loadings"
[1] "Updated dimension of data: 108 54"
Error in t.default(dataM[[2]]) : argument is not a matrix
```

It looks like the first bug is that `t.default` is called instead of `Matrix::t` on `dataM[[2]]`. But even if using the correct `t`, the result still produces an error:
```
dataNames <- rownames(data)
loadingsNames <- rownames(loadings)

dataM <- geneMatchR(data1=data, data2=loadings, data1Names=dataNames, data2Names=loadingsNames, merge=FALSE)
projection <- MatrixModels:::lm.fit.sparse(Matrix::t(dataM[[2]]), dataM[[1]])
```
```
Error in MatrixModels:::lm.fit.sparse(Matrix::t(dataM[[2]]), dataM[[1]]) : 
  incompatible dimensions of (x,y)
```

### PR DESCRIPTION
**Pull request by dimalvovs**
- implement projectR on sparseMatrix by calling the dense one in chunks;
- fix missing LinearEmbeddingMatrix class definition
- refactor

### CODE REVIEW

File: R/projectR.R [hunk 1]
```diff
@@ -82,60 +71,61 @@ setMethod("projectR",signature(data="matrix",loadings="matrix"),function(
...
 #' @aliases projectR
 setMethod("projectR",signature(data="dgCMatrix",loadings="matrix"),function(
   data, # a dataset to be projected onto
   loadings, # a matrix of continous values to be projected with unique rownames
   dataNames = NULL, # a vector with names of data rows
   loadingsNames = NULL, # a vector with names of loadings rows
-  NP=NA, # vector of integers indicating which columns of loadings object to use. The default of NP=NA will use entire matrix.
-  full=FALSE, # logical indicating whether to return the full model solution. By default only the new pattern object is returned.
-  family="gaussianff"  # VGAM family function (default: "gaussianff")
+  NP=NULL, # vector of integers indicating which columns of loadings object to use. The default of NP=NA will use entire matrix.
```
Comment (drbergman) [inline R/projectR.R:81]: update comment to match new default

Comment (drbergman) [reply R/projectR.R:81]: also, it's noteworthy to me that the default for `NP` is `NA` above and `NULL` here. Not sure if it's desired. just noting it

File: tests/testthat/test_projectR.R [hunk 2]
```diff
@@ -200,4 +200,30 @@ test_that("results are correctly formatted for P value mode",{
...
+  dense <- as.matrix(p.RNAseq6l3c3t)
+  sparse <- as(p.RNAseq6l3c3t, "sparseMatrix")
+  loadings <- CR.RNAseq6l3c3t@featureLoadings
+
+  expect_true("dgCMatrix" %in% class(sparse))
+  expect_no_error(projectR(sparse, loadings))
 
+  pdense <- projectR(dense, loadings, full=TRUE)
+  psparse <- projectR(sparse, loadings, full=TRUE)
+  expect_identical(projectR(dense, loadings),
```
Comment (drbergman) [inline tests/testthat/test_projectR.R]: Don't you want to test that `pdense` and `psparse` are identical? Not sure why here (and above) you compute projectR twice for both dense and sparse, but at least here you want `full=TRUE` inside the `expect_identical` call, yeah?

**Review by drbergman — COMMENTED** [review]
As far as I can see, this PR simplifies the code and makes it more readable. I can't quite tell what's being removed in R/projectR.R L104-126, but I'm guessing the call on new L106 handles that now. I left a couple comments throughout the changes.

Also, the PR message suggests that the `LinearEmbeddingMatrix` class def is being fixed. I can't find a place where it is being changed, let alone fixed.

File: R/projectR.R (hunk 1 above)
Comment (dimalvovs) [reply R/projectR.R:81]: yup, because `is.na(NP)` was never going to work if NP is specified:
```
> NP <- c(1,3,5)
> if(!is.na(NP)) {print("it's a bug")}
Error in if (!is.na(NP)) { : the condition has length > 1
```
is.null works fine:
```
> is.null(NP)
[1] FALSE
```
see line 85 too - I changed the check from `is.NA` to `is.null` too

File: tests/testthat/test_projectR.R (hunk 2 above)
Comment (dimalvovs) [reply tests/testthat/test_projectR.R]: exactly, thanks for spotting and that's why we need reviews! fixed in [c3fdb7a](https://github.com/genesofeve/projectR/pull/42/commits/c3fdb7a0ae7f7906aa5fd23132cae10fdb3e2635)

**Comment by dimalvovs** [comment]
@drbergman thanks very much for the review, `LinearEmbeddingMatrix` definition is fixed in https://github.com/genesofeve/projectR/pull/42/commits/5b1a15a4615792e718d3a06f67b84e5b9a497d6e
